const $=id=>document.getElementById(id),root=new URL('.',location.href),ns='http://www.w3.org/2000/svg';
let index,record,selected=-1,currentName='',loadVersion=0;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=p=>new URL(p,root).href;
function card(r){return `<button class="card ${r.name===currentName?'active':''}" data-name="${escape(r.name)}"><img src="${url(r.thumb)}" alt="" loading="lazy"><span><b>${escape(r.name)}</b><small>${r.boxes} 框 · ${escape(r.annotator)}</small><small class="${r.issues.length?'flag':''}">${r.issues.length?escape(r.issues.join('、')):'已提取坐标与 GT'}</small></span></button>`;}
function filtered(r){const q=$('search').value.trim().toLowerCase(),f=$('filter').value;if(q&&!`${r.name} ${r.annotator} ${r.group}`.toLowerCase().includes(q))return false;return f==='all'||f==='issues'&&r.issues.length>0||f==='reviewed'&&r.reviewed||f==='pending'&&r.editable&&!r.reviewed;}
function renderCards(){const rows=index.files.filter(filtered);$('visible').textContent=`显示 ${rows.length} / ${index.images} 组`;$('cards').innerHTML=rows.map(card).join('');}
function select(i){if(!record||i<0||i>=record.boxes.length)return;selected=i;for(const e of $('boxLayer').children)e.classList.toggle('selected',Number(e.dataset.index)===i);for(const e of $('gt').children)e.classList.toggle('selected',Number(e.dataset.index)===i);const b=record.boxes[i];$('selectedInfo').textContent=`#${i+1} · ${b.label} · 坐标 ${b.box.join(', ')}`;const token=$('gt').children[i];token?.scrollIntoView({block:'nearest'});}
function centerOn(i){const box=$('boxLayer').children[i];if(!box)return;const area=$('imageScroll'),r=box.getBoundingClientRect(),p=area.getBoundingClientRect();area.scrollLeft+=r.left+r.width/2-p.left-p.width/2;area.scrollTop+=r.top+r.height/2-p.top-p.height/2;}
function renderPage(meta,d){record=d;selected=-1;currentName=meta.name;$('pageName').textContent=meta.name;$('pageMeta').textContent=`${meta.width} × ${meta.height} 像素 · ${meta.boxes} 框 · 来源：${meta.group} · 标注人：${meta.annotator}`;$('editLink').hidden=!meta.editable;$('editLink').href='./?image='+encodeURIComponent(meta.name);$('gtCount').textContent=`${meta.boxes} 框 / ${[...d.gt].length} 字`;
 const scene=$('scene');scene.setAttribute('viewBox',`0 0 ${d.width} ${d.height}`);scene.setAttribute('width',d.width);scene.setAttribute('height',d.height);$('pageImage').setAttribute('href',url(meta.image));$('pageImage').setAttribute('width',d.width);$('pageImage').setAttribute('height',d.height);
 const frag=document.createDocumentFragment();for(const [i,item] of d.boxes.entries()){const [x,y,xx,yy]=item.box;const rect=document.createElementNS(ns,'rect');for(const [k,v] of Object.entries({x,y,width:xx-x,height:yy-y,'data-index':i}))rect.setAttribute(k,v);const title=document.createElementNS(ns,'title');title.textContent=`#${i+1} ${item.label}`;rect.append(title);frag.append(rect);}$('boxLayer').replaceChildren(frag);
 const gt=document.createDocumentFragment();for(const [i,item] of d.boxes.entries()){const b=document.createElement('button');b.type='button';b.dataset.index=i;b.textContent=item.label;b.title=`#${i+1} · ${item.label}`;gt.append(b);}$('gt').replaceChildren(gt);$('selectedInfo').textContent='点击图片中的框或右侧 GT，查看序号、文字和坐标。';$('zoom').value=100;setZoom();$('imageScroll').scrollTo(0,0);renderCards();history.replaceState(null,'','?image='+encodeURIComponent(meta.name));}
function setZoom(){const percent=Number($('zoom').value);$('zoomValue').textContent=percent+'%';if(record)$('scene').style.width=(record.width*percent/100)+'px';}
async function openPage(name){const meta=index.files.find(r=>r.name===name);if(!meta)return;const version=++loadVersion;$('pageName').textContent='正在加载 '+name+'…';try{const response=await fetch(url(meta.data),{cache:'no-cache'});if(!response.ok)throw Error('标注读取失败');const d=await response.json();if(version!==loadVersion)return;if(d.name!==name||d.boxes.length!==meta.boxes)throw Error('图片与标注数量不一致');renderPage(meta,d);}catch(e){$('pageName').textContent=name+' 加载失败';$('selectedInfo').textContent=e.message;}}
$('cards').onclick=e=>{const target=e.target.closest('[data-name]');if(target)openPage(target.dataset.name);};$('search').oninput=renderCards;$('filter').onchange=renderCards;$('boxLayer').onclick=e=>{const r=e.target.closest('rect[data-index]');if(r)select(Number(r.dataset.index));};$('gt').onclick=e=>{const b=e.target.closest('button[data-index]');if(b){const i=Number(b.dataset.index);select(i);centerOn(i);}};$('showBoxes').onchange=()=>$('imageScroll').classList.toggle('hide-boxes',!$('showBoxes').checked);$('zoom').oninput=setZoom;
try{const response=await fetch(url('all/index.json'),{cache:'no-cache'});if(!response.ok)throw Error('168组清单读取失败');index=await response.json();if(index.images!==168||index.files.length!==168)throw Error('清单数量不完整');$('summary').textContent=`筛选后 ${index.images} 组 · ${index.boxes.toLocaleString()} 框 · 图片、坐标与 GT 逐框对应`;renderCards();const wanted=new URLSearchParams(location.search).get('image');await openPage(index.files.some(r=>r.name===wanted)?wanted:index.files[0].name);}catch(e){$('summary').textContent=e.message;}
