const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let index,doc,meta,selected=-1,version=0,changes=[],questions=[],position=[],scrollLock=false;
const el=(tag,attrs={})=>{const n=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);return n;};
function rows(){const q=$('search').value.trim().toLowerCase(),f=$('filter').value;return index.files.filter(r=>(!q||`${r.name} ${r.annotator}`.toLowerCase().includes(q))&&(f==='all'||f==='changed'&&r.moved>0||f==='unchanged'&&!r.moved||f==='review'&&r.review));}
function renderList(){const rr=rows();$('visible').textContent=`${rr.length} / ${index.files.length} 组`;$('list').innerHTML=rr.map(r=>`<button class="card ${r.name===meta?.name?'active':''}" data-name="${esc(r.name)}"><img src="${esc(r.thumb)}" loading="lazy" alt=""><span><b>${esc(r.name)}</b><small>${r.moved?`${r.moved} 框序号变化`:'顺序未变化'}</small><small>${r.review?'有待复核项':r.moved?'已按坐标调整':'沿用原顺序'}</small></span></button>`).join('');}
function order(side){return side==='before'?doc.before.map((_,i)=>i):doc.after;}
function cls(id){return (position[id]!==id?' changed':'')+(questions.includes(id)?' question':'');}
function draw(side){const svg=$(side+'Svg');svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${doc.width} ${doc.height}`);svg.setAttribute('width',doc.width);svg.setAttribute('height',doc.height);svg.append(el('image',{href:meta.image,width:doc.width,height:doc.height}));const gt=document.createDocumentFragment(),boxes=el('g');
 order(side).forEach((id,i)=>{const b=doc.before[id],[x,y,xx,yy]=b.box;const rect=el('rect',{x,y,width:xx-x,height:yy-y,class:'box'+cls(id),'data-id':id});const title=el('title');title.textContent=`#${i+1} ${b.label}（原 #${id+1} → 新 #${position[id]+1}）`;rect.append(title);boxes.append(rect);const txt=el('text',{x,y:Math.max(8,y-1),class:cls(id),'data-id':id});txt.textContent=i+1;boxes.append(txt);const token=document.createElement('button');token.type='button';token.dataset.id=id;token.className=cls(id);token.title=title.textContent;token.textContent=b.label;gt.append(token);});svg.append(boxes,el('path',{class:'link'}));$(side+'Gt').replaceChildren(gt);$(side+'Count').textContent=`${doc.before.length} 框 / ${[...doc.before.map(b=>b.label).join('')].length} 字`;}
function zoom(){const z=Number($('zoom').value);$('zoomValue').value=z+'%';for(const side of ['before','after'])$(side+'Svg').style.width=(doc.width*z/100)+'px';}
function center(side,id){const node=$(side+'Svg').querySelector(`rect[data-id="${id}"]`);if(!node)return;const box=node.getBoundingClientRect(),area=$(side+'Scroll'),r=area.getBoundingClientRect();area.scrollLeft+=box.left+box.width/2-r.left-r.width/2;area.scrollTop+=box.top+box.height/2-r.top-r.height/2;}
function links(side){const svg=$(side+'Svg'),path=svg.querySelector('path.link');path.setAttribute('d','');if(!$('arrows').checked||selected<0)return;const ids=order(side),i=ids.indexOf(selected),neighbors=ids.slice(Math.max(0,i-1),Math.min(ids.length,i+2));path.setAttribute('d',neighbors.map((id,j)=>{const [x,y,xx,yy]=doc.before[id].box;return `${j?'L':'M'}${(x+xx)/2} ${(y+yy)/2}`;}).join(' '));}
function select(id,pan=true){selected=id;const b=doc.before[id];$('selected').textContent=`同一个框：原 #${id+1} → 新 #${position[id]+1} · GT「${b.label}」 · 坐标 ${b.box.join(', ')}${questions.includes(id)?' · 待复核':''}`;scrollLock=true;for(const side of ['before','after']){for(const n of $(side+'Svg').querySelectorAll('[data-id]'))n.classList.toggle('selected',Number(n.dataset.id)===id);for(const n of $(side+'Gt').children)n.classList.toggle('selected',Number(n.dataset.id)===id);const token=$(side+'Gt').querySelector(`[data-id="${id}"]`),gt=$(side+'Gt');if(token){const tr=token.getBoundingClientRect(),gr=gt.getBoundingClientRect();gt.scrollTop+=tr.top+tr.height/2-gr.top-gr.height/2;}if(pan)center(side,id);links(side);}requestAnimationFrame(()=>scrollLock=false);}
function step(delta){if(!changes.length)return;let i=changes.indexOf(selected);if(i<0)i=delta>0?-1:0;select(changes[(i+delta+changes.length)%changes.length]);}
async function open(name){const m=index.files.find(r=>r.name===name);if(!m)return;const v=++version;$('name').textContent='读取 '+name+'…';try{const res=await fetch(m.data,{cache:'no-cache'});if(!res.ok)throw Error('对照文件读取失败');const d=await res.json();if(v!==version)return;if(d.before.length!==d.after.length||new Set(d.after).size!==d.before.length||d.after.some(i=>!Number.isInteger(i)||i<0||i>=d.before.length))throw Error('新旧框映射不完整');doc=d;meta=m;selected=-1;position=[];d.after.forEach((old,i)=>position[old]=i);changes=d.before.map((_,i)=>i).filter(i=>position[i]!==i);questions=[...new Set(d.questions.flatMap(q=>q.indices||[]))].map(i=>i-1).filter(i=>i>=0&&i<d.before.length);$('name').textContent=name;$('meta').textContent=`${m.boxes} 框 · ${m.annotator} · ${changes.length} 框序号变化`;$('notice').textContent=d.summary;$('notes').textContent=[d.method,...d.questions.map(q=>q.message+(q.indices?.length?`（原序号 ${q.indices.slice(0,20).join('、')}${q.indices.length>20?'…':''}）`:''))].join('\n\n');$('full').href='all.html?image='+encodeURIComponent(name);$('prev').disabled=$('next').disabled=!changes.length;$('question').disabled=!questions.length;draw('before');draw('after');$('zoom').value=100;zoom();renderList();history.replaceState(null,'','?image='+encodeURIComponent(name));if(changes.length)select(changes[0]);else if(questions.length)select(questions[0]);else $('selected').textContent='本页顺序未变化，点任意框核对。';}catch(e){$('notice').textContent=e.message;}}
function download(side){if(!doc)return;const sh=order(side).map(i=>doc.before[i]);const data={version:'5.5.0',flags:{},shapes:sh.map(s=>({label:s.label,points:[[s.box[0],s.box[1]],[s.box[2],s.box[3]]],group_id:null,shape_type:'rectangle',flags:{}})),imagePath:doc.name+'.png',imageData:null,imageWidth:doc.width,imageHeight:doc.height};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=doc.name+'_'+(side==='before'?'调整前':'调整后')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('search').oninput=renderList;$('filter').onchange=renderList;$('list').onclick=e=>{const n=e.target.closest('[data-name]');if(n)open(n.dataset.name);};$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('question').onclick=()=>{if(questions.length)select(questions[(questions.indexOf(selected)+1)%questions.length]);};$('numbers').onchange=()=>document.body.classList.toggle('hide-numbers',!$('numbers').checked);$('arrows').onchange=()=>{if(doc)for(const s of ['before','after'])links(s);};$('zoom').oninput=()=>{if(doc)zoom();};$('beforeJson').onclick=()=>download('before');$('afterJson').onclick=()=>download('after');for(const side of ['before','after']){for(const kind of ['Svg','Gt'])$(side+kind).onclick=e=>{const n=e.target.closest('[data-id]');if(n)select(Number(n.dataset.id));};$(side+'Scroll').onscroll=()=>{if(scrollLock)return;scrollLock=true;const other=$(side==='before'?'afterScroll':'beforeScroll');other.scrollTop=$(side+'Scroll').scrollTop;other.scrollLeft=$(side+'Scroll').scrollLeft;requestAnimationFrame(()=>scrollLock=false);};}
try{const r=await fetch('order/index.json',{cache:'no-cache'});if(!r.ok)throw Error('对照清单读取失败');index=await r.json();$('summary').textContent=`${index.files.length} 组 · ${index.changed} 组顺序变化 · ${index.review} 组含待复核项`;renderList();const name=new URLSearchParams(location.search).get('image');await open(index.files.some(r=>r.name===name)?name:'1-52');}catch(e){$('summary').textContent=e.message;}
